---
builds:
  - env:
    - CGO_ENABLED=0
    main: main.go
    binary: bin/entrypoint
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    targets:
      - darwin_amd64
      - linux_amd64
      - windows_amd64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    format: tar.gz
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md
